/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 /* @file part_b_server.c
 * @author Can Koban
 *
 * @brief Project 1 par_b solution is following. Server side is doing exactly same thing in the part_a.
 * However, in remote procedure control aim is serving many clients from far away. Client sends its inputs and path
 * for the executable blackbox. Then, server takes them and do same thing in the part_a but it does not write to file.
 * Rather than that, it sends back the output to client and client part writes to the file when the main function ends. 
 * @Reference: Implentatiton is learned from PS 6 notes, especially from rpc example.
 */

#include <unistd.h>
#include <fcntl.h>

#include "part_b.h"

/*
 * O_WRONLY: Writing only
 * O_CREAT: Create file. If it is created already, no effect.
 * O_APPEND: Append end of the file.
*/
#define CREATE_FLAGS (O_WRONLY | O_CREAT | O_APPEND)
/**
 * S_IRUSR: Read permission for the file owner, 
 * S_IWUSR: Write permission for the file owner, 
 * S_IRGRP: Read permission for the file's group, 
 * S_IROTH: Read permission for users other than the file owner.
*/
#define CREATE_MODE (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)

void
part_b_prog_1(char *host,char *blackboxPath,char *outputPath,int x,int y)
{
	CLIENT *clnt;
	char * *result_1;
	inputs  part_b_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PART_B_PROG, PART_B_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	//Assign variables and path to the outgoing packet.
	part_b_1_arg.a=x;
	part_b_1_arg.b=y;
	strcpy(part_b_1_arg.blackboxPath,blackboxPath);

	//Call server.
	result_1 = part_b_1(&part_b_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		//If not failed, redirect result to the txt file with the given output path.
		int fd_output=open(outputPath,CREATE_FLAGS,CREATE_MODE);

		dup2(fd_output, STDOUT_FILENO);
		dup2(fd_output, STDERR_FILENO);

		printf("%s", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	//2 path and ip adress are sent to the program.
	char *host;
	char *blackboxPath;
	char *outputPath;

	if (argc < 4) {
		printf ("usage: %s blackboxPath outputPath server_host\n", argv[0]);
		exit (1);
	}

	//Integers are obtained in the client main and send to the server.
	int a;
    int b;
    scanf("%d", &a);
    scanf("%d", &b);

	blackboxPath=argv[1];
	outputPath=argv[2];
	host = argv[3];

	//From one shoul follow the part_b_prog_1() function.
	part_b_prog_1 (host,blackboxPath,outputPath,a,b);
exit (0);
}
