/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int a;
	int b;
	char blackboxPath[200];
};
typedef struct inputs inputs;

#define PART_B_PROG 0x19845673
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_b 1
extern  char ** part_b_1(inputs *, CLIENT *);
extern  char ** part_b_1_svc(inputs *, struct svc_req *);
extern int part_b_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_b 1
extern  char ** part_b_1();
extern  char ** part_b_1_svc();
extern int part_b_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
